# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('header', models.ImageField(blank=True, help_text='Upload header image for brand', null=True, upload_to='gallery/brand/header')),
                ('headline', models.CharField(blank=True, max_length=300, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('ref_url_info', models.CharField(blank=True, default='More', max_length=25, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ref_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
