# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import realestate.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realestate', '0002_property_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('listing', models.ForeignKey(on_delete=models.SET(realestate.models.get_sentinel_user), related_name='listing_interest', to='realestate.Property')),
                ('user', models.ForeignKey(on_delete=models.SET(realestate.models.get_sentinel_user), related_name='user_interest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Listing Interested User',
                'verbose_name_plural': 'Listing Interested Users',
            },
        ),
        migrations.CreateModel(
            name='Listing_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=models.SET(realestate.models.get_sentinel_user), related_name='listing_rating', to='realestate.Property')),
                ('user', models.ForeignKey(on_delete=models.SET(realestate.models.get_sentinel_user), related_name='user_rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
