# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 09:55
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_listing_interest_listing_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_ref',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
