# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 11:49
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_auto_20161226_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional cover for property', max_length=255, null=True, verbose_name='image'),
        ),
    ]
