# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_auto_20161226_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tags',
            field=models.ManyToManyField(blank=True, to='realestate.Tag'),
        ),
    ]
